#pragma once

#include <avr/io.h>

// CPU CONF
 #define F_CPU 8000000UL

// LED CONF
#define LED_PORT PORTC
#define LED_DDR DDRC
#define LED_PIN PC2

// DS18B20
#define DS_A  PD5
#define DS_B  PD7
#define DS_RESOLUTION 12

// BUTTON CONF
#define BTN_PORT PORTD
#define BTN_DDR  DDRD
#define BTN_PIN  PD3

// APP CONF
#define DISPLAY_ACTIVE_MS_TIME 60000
#define EEPROM_WRITE_CHECK_FRAME_TIMEOUT 30000
#define TEMPERATURE_FRAME_START_YEAR 2025